apiVersion: v1
kind: Pod
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  containers:
  - name: web-app
    image: naeem158/flask-web-app:latest
    ports:
    - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-throttle: "4"
  labels:
    app: web-app
spec:
  selector:
    app: web-app
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer